# -*- coding: utf-8 -*-
"""domingo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Boszc6MAc9dSK2ZrQCziJzO3preZ66pt

**Exercício de função:**

**1 - Crie uma função que calcula a área de um terreno a partir da largura e do comprimento do terreno;**
**2 - Em uma célula separada, peça para o usuário digitar a largura e o comprimento (ambos em metros);**
**3 - Utilize a função que calcula a área para calcular a área e informar o usuário do seu sistema.**
"""

def calc_area(largura, comprimento):
  area = largura * comprimento
  # print('A área do terreno é {}m²'.format(area))
  return area

largura = int(input('Digite a largura do terreno: '))
comprimento = int(input('Digite o comprimento do terreno: '))

area = calc_area(largura, comprimento)

