# -*- coding: utf-8 -*-
"""exercios sabado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11mAaQ8w8oALIOvUA0gy54h7LW4ZcGZOQ

**Primeiro exercício de sábado de manhã (pra aquecer): escrevem uma célula no Colab que recebe um texto (usando o método input()) e depois apresentem o texto todo em letras minúsculas (usando o método .lower())**
"""

nome = input('Digite seu nome completo:')

print(nome.lower())

"""**Usando os métodos input() e string.count(), imprima True se o e-mail informado tiver apenas um arroba (@) e False caso contrário.**"""

email = input('Qual teu e-mail, {}?\n'.format(nome.split(' ')[0]))
email = email.lower()
print(email)

print(email.count('@'))

"""**Usando o método input e o laço while, solicite que seja digitado um número entre 1 e 10, caso um número inválido seja digitado, avise o usuário e peça o número novamente; caso um número válido seja digitado, imprima o número.**"""

numero = 0
while numero < 1 or numero > 10:
  numero = int(input('Digite um número ente 1 e 10: \n'))

print('\nNumero digitado corretamente: {}'.format(numero))

numero = 0
lista_excecao = list(range(1, 11, 1))
while numero not in lista_excecao:
  numero = int(input('Digite um número ente 1 e 10: \n'))

print('\nNumero digitado corretamente: {}'.format(numero))

"""**Imprimir na tela de 0 a 9 usando o for - range**"""

for i in range (10):
  print(i)

"""**AJUSTAR PARA MINUSCULAS**"""

frases = ['As Palavras Dessa Frase Têm A Primeira Letra Maiúscula ',

          'ESSA FRASE ESTÁ TODA EM LETRA MAIÚSCULA ',

          'EsSa FrAsE esTÁ UMa BaGUnÇa'

]

[print(texto.lower()) for texto in frases];

"""**Exercício: avaliador de temperatura**
1 - Usuário digita a temperatura
2 - Se a temperatura digitada for menor que 10 graus, informe "Está muito frio, procure abrigo!")
3 - Caso contrário informe "Não está tão frio assim."
4 - No final escrever: "Obrigado por usar o avaliador de temperatura."
"""

temperatura = int(input('Digite a temperatura atual: \n'))

print('\nTemperatura atual: {}'.format(temperatura))

if (temperatura < 10):
  print("Está muito frio, procure abrigo!")
else:
  print("Não está tão frio assim.")

"""**Usando o método input e o condicional if, escreva um programa em que o usuário informa sua idade e o programa que imprime a classificação da pessoa conforme abaixo:**
Criança (menor de 12 anos)
Adolescente (entre 12 e 18 anos)
Adulto (entre 19 e 60 anos) e
Idoso (maior que 60 anos)
"""

idade = int(input('Digite a sua idade: \n'))

if (idade < 12):
  print('Criança')
elif (idade <= 18):
  print('Adolescente')
elif (idade <= 60):
  print('Adulto')
else:
  print('Idoso')

"""**Gere um número aleatório entre 1 e 9 (incluindo 1 e 9) usando random do Python. Peça ao usuário para adivinhar o número e diga se ele adivinhou muito baixo, muito alto ou exatamente certo. (Dica: lembre-se de usar input() para receber o número do usuário)**
Continue o jogo até que o usuário digitar 0
Mostre quantos chutes o usuário precisou para acertar
"""

from random import randint # Import the random module

for _ in range(3):
  numero_pensado = randint(1, 9)  # Use random.random() to generate a random number
  for tentativa in range(1, 5, 1):
      numero = int(input('\nTente adivinhar o número que pensei: \n'))

      if numero == numero_pensado:
          print('Você acertou! O número pensado foi {}'.format(numero_pensado))
          break
      elif numero < numero_pensado:
          print('O número pensado é maior')
      else:
          print('O número pensado é menor')

      print('Você tem apenas {} tentativa(s)'.format(5-tentativa))

"""**1 - Criar uma lista de compras (entre 5 e 10 itens);**
**2 - Ordenar em ordem alfabética a lista;**
**3 - Apresentar a quantidade de itens da lista;**
**4 - Apresentar a lista toda.**
"""

from random import randint # Import the random module
tamanho_lista = randint(5, 10)
lista_compra = []
while not(len(lista_compra) > tamanho_lista):
  nome_item = (input('Digite o nome de um item para a sua lista de compras: \n')).capitalize()
  if nome_item in lista_compra:
    print('O item {} já está na lista'.format(nome_item))
    continue
  lista_compra.append(nome_item)
lista_compra.sort()
print('\nA lista de compras possui {} itens, que são:'.format(len(lista_compra)))
print('\n'.join(lista_compra))

"""**Crie um programa que lê vários números e os coloca em uma lista. Depois disso, mostre: Quantos números foram digitados; A lista de valores, ordenada de forma decrescente; Se o valor 5 está ou não presente na lista.**"""

from random import randint # Import the random module
tamanho_lista = randint(5, 10)
lista_numerica = []
while not(len(lista_numerica) > tamanho_lista):
  numero = int(input('Digite o número: \n'))
  if numero in lista_numerica:
    print('O numero {} já está na lista'.format(numero))
    continue
  lista_numerica.append(numero)

lista_numerica.sort()
print('\nLista de números: {}'.format(lista_numerica))
print('Quantidade de números digitados: {}'.format(len(lista_numerica)))
if 5 in lista_numerica:
  print('O número 5 está na lista')
else:
  print('O número 5 não está na lista')

"""**Criem um matriz com 4 linhas e 5 colunas**
Formada apenas por inteiros (positivos e negativos) e apresente essa matriz
"""

from random import randint # Import the random module
matriz = []
for linha in range(4):
  lista_temporaria = []
  while not(len(lista_temporaria) > 5):
    numero_aleatorio = randint(-5, 5)
    if numero_aleatorio in matriz:
      print('O numero {} já está na matriz {}'.format(numero_aleatorio, matriz))
      continue
    lista_temporaria.append(numero_aleatorio)
  matriz.append(lista_temporaria)
print(matriz)
print('\n')
matriz

lista1

"""**Crie um dicionário com o nome e data de nascimento de 6 celebridades:**
**Milton Nascimento (26/10/1942), Anitta (30/03/1993), Neymar(05/02/1992), Pelé (23/10/1940), Djavan (27/01/1949) e Renato Russo (27/03/1960).**

**Informe o usuário de quais celebridades seu programa conhece a data de nascimento.**

**Pergunte de quem o usuário gostaria de saber a data de nascimento.**

**Caso ele digite um nome válido, informe a data de nascimento daquela pessoa.**

**Caso ele digite um nome inválido, informe que seu programa não sabe a data de nascimento daquela pessoa.**
"""

celebridades = {'Milton Nascimento': '26/10/1942',
                'Anitta': '30/03/1993',
                'Neymar': '05/02/1992',
                'Pelé': '23/10/1940',
                'Djavan': '27/01/1949',
                'Renato Russo' :'27/03/1960'
                }

print('Segue o nome das celebridades as quais conheço:')
for celebridade in celebridades:
  print('   '+ celebridade)

quero_ver = input('Quem gostaria de saber a data de nascimento?')

if (quero_ver in celebridades):
  print('A data de nascimento de {} é {}'.format(quero_ver, celebridades[quero_ver]))
else:
  print('Não conheço a data de nascimento de {}'.format(quero_ver))